### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by subeeshvasu** [zekunhao1995/DualSDF#1]
Hi,

Can you please mention the pytorch version (and other requirements) for this package?

Thanks.

**Comment by zekunhao1995** [comment]
Hi Subeesh,

The code was developed with Python 3.6 and Pytorch 1.4. Other dependencies are:  
- `opencv-python` (Only for running the demo)  
- `tensorboardX` (Only for training)  

I will update README to reflect these requirements.
